### ISSUE TITLE
AI and EPS Logo Artwork for Print Output.

### ISSUE THREAD

**Issue by charlieartist** [elmsln/elmsln-logos#4]
Hi, Charlieartist here--I know of your work though @btopro, and since I needed to convert this artwork for use in Drupal GovCon sponsorship materials, thought it would be good to make these files available for others who may need them.

The files are set (listed in their names) as for use with RGB, CMYK, black (solid) and reversed.

**Comment by btopro** [comment]
#5 excellent, thank you! :)
